### ISSUE TITLE
Wrong syntax for create_sms in README file

### ISSUE THREAD

**Issue by harley** [blythedunham/smsonrails#1]
Instead of
<code>
  SmsOnRails::Outbound.create_sms '11234567890', 'Send this test message', :send_immediately => true
</code>
 which creates an instance with no phone number or message because it tried to look up the above message as phone number.  This works:
<code>
  SmsOnRails::Outbound.create_sms 'Send this test message', '11234567890', :send_immediately => true
</code>

Meaning the order of message and number should be exchanged in the instruction.

Thanks for the plugin

**Comment by blythedunham** [comment]
Changed docs
